//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceReporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TracePath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TracePath"]));
            }
            set {
                this["TracePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SymbolsPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SymbolsPath"]));
            }
            set {
                this["SymbolsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BuildName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BuildName"]));
            }
            set {
                this["BuildName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection StartEventName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StartEventName"]));
            }
            set {
                this["StartEventName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection StartEventParameter1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StartEventParameter1"]));
            }
            set {
                this["StartEventParameter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection StartEventParameter2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StartEventParameter2"]));
            }
            set {
                this["StartEventParameter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EndEventName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EndEventName"]));
            }
            set {
                this["EndEventName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EndEventParameter1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EndEventParameter1"]));
            }
            set {
                this["EndEventParameter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EndEventParameter2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EndEventParameter2"]));
            }
            set {
                this["EndEventParameter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Notes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Notes"]));
            }
            set {
                this["Notes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ScenarioName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScenarioName"]));
            }
            set {
                this["ScenarioName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ResultFileName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResultFileName"]));
            }
            set {
                this["ResultFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SettingsProfile {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SettingsProfile"]));
            }
            set {
                this["SettingsProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FirstLaunch {
            get {
                return ((int)(this["FirstLaunch"]));
            }
            set {
                this["FirstLaunch"] = value;
            }
        }
    }
}
